export default {
    users: [],
    user: [],
    userNavbar: [],
    userFriend: [],
    userRequest: [],
    post: [],
    posts: [],
    animalPost: [],
    animals: [],
    selectAnimal: [],
    animal: [],
    storyFriend: [],
    stories: [],
    userPhotos: [],
    animalCategory: [],
    story: [],
    authUser: [],
    comments: [],
    userLogin: [],
    animalFollows: [],
    friendRequest: [],
    friends: [],
    friendsAnimal: [],
    searchUsers: [],
    getFriendRequest: [],
    loading: true
}