export default {
    users: [],
    user: [],
    userNavbar: [],
    userFriend: [],
    userRequest: [],
    post: [],
    posts: [],
    animalPost: [],
    animals: [],
    selectAnimal: [],
    animal: [],
    storyFriend: [],
    userPhotos: [],
    animalCategory: [],
    story: [],
    authUser: [],
    comments: [],
    userLogin: [],
    animalFollows: []
}