export const baseUrl = "https://localhost:44320/api";

//---- Friend Request action type ----
export const GET_FRIEND_REQUEST_SUCCESS = "GET_FRIEND_REQUEST_SUCCESS";
export const GET_FRIEND_REQUEST_ERROR = "GET_FRIEND_REQUEST_ERROR";


export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";
export const ADD_FRIEND_ERROR = "ADD_FRIEND_ERROR";

export const UN_FRIEND_SUCCESS = "UN_FRIEND_SUCCESS";
export const UN_FRIEND_ERROR = "UN_FRIEND_ERROR";

export const DECLINED_FRIEND_SUCCESS = "DECLINED_FRIEND_SUCCESS";
export const DECLINED_FRIEND_ERROR = "DECLINED_FRIEND_ERROR";

export const BLOCK_FRIEND_SUCCESS = "BLOCK_FRIEND_SUCCESS";
export const BLOCK_FRIEND_ERROR = "BLOCK_FRIEND_ERROR";

export const CONFIRM_FRIEND_SUCCESS = "CONFIRM_FRIEND_SUCCESS";
export const CONFIRM_FRIEND_ERROR = "CONFIRM_FRIEND_ERROR";

//---- Friend GET action type ----
export const GET_ALL_FRIENDS_SUCCESS = "GET_ALL_FRIENDS_SUCCESS";
export const GET_ALL_FRIENDS_ERROR = "GET_ALL_FRIENDS_ERROR";

//---- Animal GET action type 
export const GET_FRIEND_ANIMALS_SUCCESS = "GET_ANIMALS_FRIEND_SUCCESS";
export const GET_FRIEND_ANIMALS_ERROR = "GET_ANIMALS_FRIEND_ERROR";

export const GET_ANIMAL_PHOTOS_SUCCESS = "GET_ANIMAL_PHOTOS_SUCCESS";
export const GET_ANIMAL_PHOTOS_ERROR = "GET_ANIMAL_PHOTOS_ERROR";

export const GET_ANIMAL_SUCCESS = "GET_ANIMAL_SUCCESS";
export const GET_ANIMAL_ERROR = "GET_ANIMAL_ERROR";

//---- Animal POST actio type
export const ANIMAL_CHANGE_PROFILE_SUCCESS = "ANIMAL_CHANGE_PROFILE_SUCCESS";
export const ANIMAL_CHANGE_PROFILE_ERROR = "ANIMAL_CHANGE_PROFILE_ERROR";

export const ANIMAL_CHANGE_COVER_SUCCESS = "ANIMAL_CHANGE_PROFILE_SUCCESS";
export const ANIMAL_CHANGE_COVER_ERROR = "ANIMAL_CHANGE_PROFILE_ERROR";

//----User search action type
export const GET_SEARCH_SUCCESS = "GET_SEARCH_SUCCESS";
export const GET_SEARCH_ERROR = "GET_SEARCH_ERROR";




export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_POST_SUCCESS = "GET_USER_POST_SUCCESS";

export const GET_USER_FRIEND_SUCCESS = "GET_USER_FRIEND_SUCCESS";
export const POST_FRIEND_CONFIRM_SUCCESS = "POST_FRIEND_CONFIRM_SUCCESS";

export const GET_USER_NAVBAR_SUCCESS = "GET_USER_NAVBAR_SUCCESS";

export const GET_FRIEND_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const POST_POST_CREATE_SUCCESS = "POST_POST_CREATE_SUCCESS";
export const POST_POST_CREATE_EROOR = "POST_POST_CREATE_ERROR";

export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const UNLIKE_POST_SUCCESS = "UNLIKE_POST_SUCCESS";

export const POST_COMMENT_CREATE_SUCCESS = "POST_COMMENT_CREATE_SUCCESS";
export const POST_COMMENT_CREATE_ERROR = "POST_COMMENT_CREATE_ERROR";

export const GET_ANIAML_USER_SUCCESS = "GET_ANIAML_USER_SUCCESS";

export const GET_STORY_SUCCESS = "GET_STORY_SUCCESS";
export const POST_STORY_SUCCESS = "POST_STORY_SUCCESS";
export const GET_FRIEND_STORY_SUCCESS = "GET_FRIEND_STORY_SUCCESS";

export const GET_ANIMAL_POST_SUCCESS = "GET_ANIMAL_POST_SUCCESS";

export const POST_REGISTER_SUCCESS = "POST_REGISTER_SUCCESS";
export const POST_REGISTER_FAIL = "POST_REGISTER_FAIL";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";
export const POST_LOGIN_FAIL = "POST_LOGIN_FAIL";
export const USER_LOADDED = "USER_LOADDED";

export const ANIMAL_FOLLOW_SUCCESS = "ANIMAL_FOLLOW_SUCCESS";

export const BIO_CHANGE_SUCCESS = "BIO_CHANGE_SUCCESS";

export const PROFILE_CREATE_SUCCESS = "PROFILE_CREATE_SUCCESS";

export const GET_PHOTOS_SUCCESS = "GET_PHOTOS_SUCCESS";

export const GET_ANIMAL_CATEGORY_SUCCESS = "GET_ANIMAL_CATEGORY_SUCCESS";

export const CREATE_ANIMAL_SUCCESS = "CREATE_ANIMAL_SUCCESS";

export const GET_SELECT_ANIMAL_SUCCESS = "GET_SELECT_ANIMAL_SUCCESS";

export const GET_BLOCK_USERS_SUCCESS = "GET_BLOCK_USERS_SUCCESS";

export const GET_USER_LOGIN_SUCCESS = "GET_USER_LOGIN_SUCCESS";

export const DELETE_STORY_SUCCESS = "DELETE_STORY_SUCCESS";
export const ARCHIVE_STORY_SUCCESS = "ARCHIVE_STORY_SUCCESS";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_USER_FOLLOWS_ANIMAL = "GET_USER_FOLLOWS_ANIMAL";

export const GET_ONLY_USER_PHOTOS = "GET_ONLY_USER_PHOTOS";

export const POST_SAVE_SUCCESS = "POST_SAVE_SUCCESS";

export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";

export const GET_STORIES_SUCCESS = "GET_STORIES_SUCCESS";