export const baseUrl = "https://localhost:44320/api";

//---- Friend Request action type ----
export const GET_FRIEND_REQUEST_SUCCESS = "GET_FRIEND_REQUEST_SUCCESS";
export const GET_FRIEND_REQUEST_ERROR = "GET_FRIEND_REQUEST_ERROR";


export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";
export const ADD_FRIEND_ERROR = "ADD_FRIEND_ERROR";

export const UN_FRIEND_SUCCESS = "UN_FRIEND_SUCCESS";
export const UN_FRIEND_ERROR = "UN_FRIEND_ERROR";

export const DECLINED_FRIEND_SUCCESS = "DECLINED_FRIEND_SUCCESS";
export const DECLINED_FRIEND_ERROR = "DECLINED_FRIEND_ERROR";

export const BLOCK_FRIEND_SUCCESS = "BLOCK_FRIEND_SUCCESS";
export const BLOCK_FRIEND_ERROR = "BLOCK_FRIEND_ERROR";

export const CONFIRM_FRIEND_SUCCESS = "CONFIRM_FRIEND_SUCCESS";
export const CONFIRM_FRIEND_ERROR = "CONFIRM_FRIEND_ERROR";

//---- Friend GET action type ----
export const GET_ALL_FRIENDS_SUCCESS = "GET_ALL_FRIENDS_SUCCESS";
export const GET_ALL_FRIENDS_ERROR = "GET_ALL_FRIENDS_ERROR";

//---- Animal GET action type 
export const GET_ALL_ANIMALS_SUCCESS = "GET_ALL_ANIMALS_SUCCESS";
export const GET_ALL_ANIMALS_ERROR = "GET_ALL_ANIMALS_ERROR";

export const GET_FRIEND_ANIMALS_SUCCESS = "GET_ANIMALS_FRIEND_SUCCESS";
export const GET_FRIEND_ANIMALS_ERROR = "GET_ANIMALS_FRIEND_ERROR";

export const GET_ANIMAL_PHOTOS_SUCCESS = "GET_ANIMAL_PHOTOS_SUCCESS";
export const GET_ANIMAL_PHOTOS_ERROR = "GET_ANIMAL_PHOTOS_ERROR";

export const GET_ANIMAL_SUCCESS = "GET_ANIMAL_SUCCESS";
export const GET_ANIMAL_ERROR = "GET_ANIMAL_ERROR";

export const GET_ANIMAL_USER_SUCCESS = "GET_ANIAML_USER_SUCCESS";
export const GET_ANIMAL_USER_ERROR = "GET_ANIAML_USER_ERROR";

export const GET_ANIMAL_CATEGORY_SUCCESS = "GET_ANIMAL_CATEGORY_SUCCESS";
export const GET_ANIMAL_CATEGORY_ERROR = "GET_ANIMAL_CATEGORY_ERROR";

export const CREATE_ANIMAL_SUCCESS = "CREATE_ANIMAL_SUCCESS";
export const CREATE_ANIMAL_ERROR = "CREATE_ANIMAL_ERROR";

export const GET_SELECT_ANIMAL_SUCCESS = "GET_SELECT_ANIMAL_SUCCESS";
export const GET_SELECT_ANIMAL_ERROR = "GET_SELECT_ANIMAL_ERROR";

//---- Animal POST action type
export const ANIMAL_CHANGE_PROFILE_SUCCESS = "ANIMAL_CHANGE_PROFILE_SUCCESS";
export const ANIMAL_CHANGE_PROFILE_ERROR = "ANIMAL_CHANGE_PROFILE_ERROR";

export const ANIMAL_CHANGE_COVER_SUCCESS = "ANIMAL_CHANGE_PROFILE_SUCCESS";
export const ANIMAL_CHANGE_COVER_ERROR = "ANIMAL_CHANGE_PROFILE_ERROR";

export const ANIMAL_FOLLOW_SUCCESS = "ANIMAL_FOLLOW_SUCCESS";
export const ANIMAL_FOLLOW_ERROR = "ANIMAL_FOLLOW_ERROR";

//---- Animal PUT action type
export const ANIMAL_PROFILE_UPDATE_SUCCESS = "ANIMAL_PROFILE_UPDATE_SUCCESS";
export const ANIMAL_PROFILE_UPDATE_ERROR = "ANIMAL_PROFILE_UPDATE_ERROR";
//----User search action type
export const GET_SEARCH_SUCCESS = "GET_SEARCH_SUCCESS";
export const GET_SEARCH_ERROR = "GET_SEARCH_ERROR";
//----

//----User Authenticate action type
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_ERROR = "USER_REGISTER_ERROR";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

export const USER_LOADDED = "USER_LOADDED";
export const USER_LOGOUT = "USER_LOGOUT";
//----

//----User GET actiontype 
export const GET_All_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_All_USERS_ERROR = "GET_USERS_ERROR";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const GET_USER_PHOTOS_SUCCESS = "GET_USER_PHOTOS_SUCCESS";
export const GET_USER_PHOTOS_ERROR = "GET_USER_PHOTOS_ERROR";

export const GET_ONLY_USER_PHOTOS_SUCCESS = "GET_ONLY_USER_PHOTOS_SUCCESS";
export const GET_ONLY_USER_PHOTOS_ERROR = "GET_ONLY_USER_PHOTOS_ERROR";

export const GET_BLOCK_USERS_SUCCESS = "GET_BLOCK_USERS_SUCCESS";
export const GET_BLOCK_USERS_ERROR = "GET_BLOCK_USERS_ERROR";

export const GET_USER_LOGIN_SUCCESS = "GET_USER_LOGIN_SUCCESS";
export const GET_USER_LOGIN_ERROR = "GET_USER_LOGIN_ERROR";

export const GET_USER_FOLLOWS_ANIMAL_SUCCESS = "GET_USER_FOLLOWS_ANIMAL_SUCCESS";
export const GET_USER_FOLLOWS_ANIMAL_ERROR = "GET_USER_FOLLOWS_ANIMAL_ERROR";
//----
//----User POST action type
export const PROFILE_CREATE_SUCCESS = "PROFILE_CREATE_SUCCESS";
export const PROFILE_CREATE_ERROR = "PROFILE_CREATE_ERROR";

export const COVER_CREATE_SUCCESS = "COVER_CREATE_SUCCESS";
export const COVER_CREATE_ERROR = "COVER_CREATE_ERROR";

export const BIO_CHANGE_SUCCESS = "BIO_CHANGE_SUCCESS";
export const BIO_CHANGE_ERROR = "BIO_CHANGE_ERROR";
//----
//----Post GET action type 
export const GET_FRIEND_ALL_POSTS_SUCCESS = "GET_FRIEND_ALL_POSTS_SUCCESS";
export const GET_FRIEND_ALL_POSTS_ERROR = "GET_FRIEND_ALL_POSTS_ERROR";

export const GET_USER_POST_SUCCESS = "GET_USER_POST_SUCCESS";
export const GET_USER_POST_ERROR = "GET_USER_POST_ERROR";

export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POST_SUCCESS";
export const GET_ALL_POSTS_ERROR = "GET_ALL_POST_ERROR";

export const GET_ANIMAL_POST_SUCCESS = "GET_ANIMAL_POST_SUCCESS";
export const GET_ANIMAL_POST_ERROR = "GET_ANIMAL_POST_ERROR";

export const GET_POST_ARCHIVE_SUCCESS = "GET_POST_ARCHIVE_SUCCESS";
export const GET_POST_ARCHIVE_ERROR = "GET_POST_ARCHIVE_ERROR";

export const GET_POST_RECYCLE_SUCCESS = "GET_POST_RECYCLE_SUCCESS";
export const GET_POST_RECYCLE_ERROR = "GET_POST_RECYCLE_ERROR";

export const GET_POST_SAVE_SUCCESS = "GET_POST_SAVE_SUCCESS";
export const GET_POST_SAVE_ERROR = "GET_POST_SAVE_ERROR";

//----
//---- Post POST action type 
export const POST_SAVE_SUCCESS = "POST_SAVE_SUCCESS";
export const POST_SAVE_ERROR = "POST_SAVE_ERROR";

export const POST_CERATE_SUCCESS = "POST_CERATE_SUCCESS";
export const POST_CERATE_ERROR = "POST_CERATE_ERROR";

//----

//----Post PATCH action type
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_ERROR = "POST_DELETE_ERROR";

export const POST_ARCHIVE_SUCCESS = "POST_ARCHIVE_SUCCESS";
export const POST_ARCHIVE_ERROR = "POST_ARCHIVE_ERROR";
//----
//----Like POST action type 
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_ERROR = "LIKE_POST_ERROR";
//----
//----Story GET action type 

export const GET_USER_STORIES_SUCCESS = "GET_STORY_SUCCESS";
export const GET_USER_STORIES_ERROR = "GET_STORY_SUCCESS";

export const GET_FRIEND_STORIES_SUCCESS = "GET_FRIEND_STORIES_SUCCESS";
export const GET_FRIEND_STORIES_ERROR = "GET_FRIEND_STORIES_ERROR";

export const GET_ALL_STORIES_SUCCESS = "GET_ALL_STORIES_SUCCESS_SUCCESS";
export const GET_ALL_STORIES_ERROR = "GET_ALL_STORIES_SUCCESS_ERROR";

export const GET_STORY_ARCHIVE_SUCCESS = "GET_STORY_ARCHIVE_SUCCESS";
export const GET_STORY_ARCHIVE_ERROR = "GET_STORY_ARCHIVE_ERROR";

export const GET_STORY_RECYCLE_SUCCESS = "GET_STORY_RECYCLE_SUCCESS";
export const GET_STORY_RECYCLE_ERROR = "GET_STORY_RECYCLE_ERROR";
//----
//----Story POST action type 
export const STORY_CREATE_SUCCESS = "STORY_CREATE_SUCCESS";
export const STORY_CREATE_ERROR = "STORY_CREATE_ERROR";

export const DELETE_STORY_SUCCESS = "DELETE_STORY_SUCCESS";
export const DELETE_STORY_ERROR = "DELETE_STORY_ERROR";

export const ARCHIVE_STORY_SUCCESS = "ARCHIVE_STORY_SUCCESS";
export const ARCHIVE_STORY_ERROR = "ARCHIVE_STORY_ERROR";

export const COMMENT_CREATE_SUCCESS = "COMMENT_CREATE_SUCCESS";
export const COMMENT_CREATE_ERROR = "COMMENT_CREATE_ERROR";

//----
//----Page GET action type 
export const GET_ALL_PAGE_SUCCESS = "GET_ALL_PAGE_SUCCESS";
export const GET_ALL_PAGE_ERROR = "GET_ALL_PAGE_ERROR";

export const GET_PAGE_SUCCESS = "GET_PAGE_SUCCESS";
export const GET_PAGE_ERROR = "GET_PAGE_ERROR";

export const GET_PAGE_PHOTOS_SUCCESS = "GET_PAGE_PHOTOS_SUCCESS";
export const GET_PAGE_PHOTOS_ERROR = "GET_PAGE_PHOTOS_ERROR";

export const GET_PAGE_ALL_POST_SUCCESS = "GET_PAGE_ALL_POST_SUCCESS";
export const GET_PAGE_ALL_POST_ERROR = "GET_PAGE_ALL_POST_ERROR";
//----
//---- Page POST action type 
export const PAGE_CHANGE_PROFILE_SUCCESS = "PAGE_CHANGE_PROFILE_SUCCESS";
export const PAGE_CHANGE_PROFILE_ERROR = "PAGE_CHANGE_PROFILE_ERROR";

export const PAGE_CHANGE_COVER_SUCCESS = "PAGE_CHANGE_COVER_SUCCESS";
export const PAGE_CHANGE_COVER_ERROR = "PAGE_CHANGE_COVER_ERROR";

//----

export const GET_USER_FRIEND_SUCCESS = "GET_USER_FRIEND_SUCCESS";
export const POST_FRIEND_CONFIRM_SUCCESS = "POST_FRIEND_CONFIRM_SUCCESS";
export const GET_USER_NAVBAR_SUCCESS = "GET_USER_NAVBAR_SUCCESS";

export const GET_PHOTOS_SUCCESS = "GET_PHOTOS_SUCCESS";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_ONLY_USER_PHOTOS = "GET_ONLY_USER_PHOTOS";


